STYLES = {
    "sbcape": {
        "levels": [100, 250, 500, 1000, 1500, 2000, 2500, 3000, 4000, 5000],
        "cmap": "YlOrRd",
        "label": "SBCAPE (J/kg)",
        "extend": "max",
    },
    "mlcape": {
        "levels": [100, 250, 500, 1000, 1500, 2000, 2500, 3000, 4000],
        "cmap": "YlOrRd",
        "label": "MLCAPE (J/kg)",
        "extend": "max",
    },
    "mucape": {
        "levels": [100, 250, 500, 1000, 1500, 2000, 2500, 3000, 4000, 5000],
        "cmap": "YlOrRd",
        "label": "MUCAPE (J/kg)",
        "extend": "max",
    },
    "sb3cape": {
        "levels": [25, 50, 100, 150, 200, 300, 400, 500],
        "cmap": "YlOrRd",
        "label": "SB3CAPE (J/kg)",
        "extend": "max",
    },
    "sbcin": {
        "levels": [-300, -250, -200, -150, -100, -75, -50, -25],
        "cmap": "BuPu_r",
        "label": "SBCIN (J/kg)",
        "extend": "min",
    },
    "srh_01km": {
        "levels": [50, 100, 150, 200, 300, 400, 500],
        "cmap": "RdPu",
        "label": "0-1km SRH (m\u00b2/s\u00b2)",
        "extend": "max",
    },
    "srh_03km": {
        "levels": [100, 200, 300, 400, 500, 600, 800],
        "cmap": "RdPu",
        "label": "0-3km SRH (m\u00b2/s\u00b2)",
        "extend": "max",
    },
    "shear_01km": {
        "levels": [5, 10, 15, 20, 25, 30, 35, 40],
        "cmap": "plasma",
        "label": "0-1km Shear (kt)",
        "extend": "max",
    },
    "shear_06km": {
        "levels": [10, 20, 30, 40, 50, 60, 70, 80],
        "cmap": "plasma",
        "label": "0-6km Shear (kt)",
        "extend": "max",
    },
    "stp": {
        "levels": [0.5, 1, 2, 3, 5, 8, 12],
        "cmap_colors": [
            "#ffffb2",
            "#fecc5c",
            "#fd8d3c",
            "#f03b20",
            "#bd0026",
            "#67000d",
        ],
        "label": "Sig Tornado Parameter",
        "extend": "max",
    },
    "scp": {
        "levels": [1, 2, 4, 6, 8, 10, 15],
        "cmap": "OrRd",
        "label": "Supercell Composite",
        "extend": "max",
    },
    "t2m_f": {
        "levels_range": (-20, 115, 5),
        "cmap": "RdYlBu_r",
        "label": "Temperature (\u00b0F)",
        "extend": "both",
    },
    "td2m_f": {
        "levels_range": (-10, 80, 5),
        "cmap": "BrBG",
        "label": "Dewpoint (\u00b0F)",
        "extend": "both",
    },
    "theta_e_sfc": {
        "levels_range": (290, 370, 5),
        "cmap": "RdYlBu_r",
        "label": "Sfc Theta-e (K)",
        "extend": "both",
    },
    "theta_e_850": {
        "levels_range": (280, 360, 5),
        "cmap": "RdYlBu_r",
        "label": "850mb Theta-e (K)",
        "extend": "both",
    },
    "wetbulb_sfc": {
        "levels_range": (-25, 35, 2),
        "cmap": "RdYlBu_r",
        "label": "Sfc Wet Bulb (\u00b0C)",
        "extend": "both",
    },
    "mslp": {
        "levels_range": (960, 1050, 4),
        "cmap": None,
        "label": "MSLP (hPa)",
        "contour_only": True,
    },
    "mixing_ratio": {
        "levels_range": (2, 24, 2),
        "cmap": "Greens",
        "label": "Mixing Ratio (g/kg)",
        "extend": "max",
    },
    "pw": {
        "levels_range": (5, 60, 5),
        "cmap": "GnBu",
        "label": "Precipitable Water (mm)",
        "extend": "max",
    },
    "lr_700_500": {
        "levels_range": (4, 10, 0.5),
        "cmap": "Reds",
        "label": "700-500mb Lapse Rate (\u00b0C/km)",
        "extend": "max",
    },
    "refc": {
        "nws_radar": True,
        "label": "Composite Reflectivity (dBZ)",
    },
    # --- Stability Indices ---
    "k_index": {
        "levels": [15, 20, 25, 30, 35, 40],
        "cmap": "YlOrRd",
        "label": "K-Index",
        "extend": "both",
    },
    "total_totals": {
        "levels": [40, 44, 48, 50, 52, 55, 60],
        "cmap": "YlOrRd",
        "label": "Total Totals Index",
        "extend": "both",
    },
    "lifted_index": {
        "levels": [-10, -8, -6, -4, -2, 0, 2, 4, 6],
        "cmap": "RdYlBu",
        "label": "Lifted Index (\u00b0C)",
        "extend": "both",
    },
    "boyden": {
        "levels": [90, 92, 94, 95, 96, 97, 98, 100],
        "cmap": "OrRd",
        "label": "Boyden Index",
        "extend": "both",
    },
    "sweat": {
        "levels": [100, 150, 200, 250, 300, 400, 500, 600],
        "cmap": "YlOrRd",
        "label": "SWEAT Index",
        "extend": "max",
    },
    # --- Surface Parameters ---
    "heat_index": {
        "levels_range": (80, 130, 5),
        "cmap": "YlOrRd",
        "label": "Heat Index (\u00b0F)",
        "extend": "max",
    },
    "windchill": {
        "levels_range": (-50, 40, 5),
        "cmap": "BuPu_r",
        "label": "Wind Chill (\u00b0F)",
        "extend": "both",
    },
    "ffwi": {
        "levels": [10, 20, 30, 40, 50, 60, 70, 80, 100],
        "cmap": "YlOrRd",
        "label": "Fosberg Fire Weather Index",
        "extend": "max",
    },
    "hdw": {
        "levels": [50, 100, 200, 400, 600, 800, 1000, 1500],
        "cmap": "YlOrRd",
        "label": "Hot-Dry-Windy Index",
        "extend": "max",
    },
    "wbgt": {
        "levels_range": (70, 110, 2),
        "cmap": "YlOrRd",
        "label": "WBGT (\u00b0F)",
        "extend": "both",
    },
    # --- Additional Composites ---
    "ehi": {
        "levels": [0.5, 1, 2, 3, 5, 8, 12],
        "cmap": "OrRd",
        "label": "Energy-Helicity Index",
        "extend": "max",
    },
    "ship": {
        "levels": [0.5, 1, 1.5, 2, 3, 4, 5],
        "cmap_colors": [
            "#ffffb2",
            "#fecc5c",
            "#fd8d3c",
            "#f03b20",
            "#bd0026",
            "#67000d",
        ],
        "label": "Sig Hail Parameter",
        "extend": "max",
    },
    "dcape": {
        "levels": [200, 400, 600, 800, 1000, 1500, 2000],
        "cmap": "BuPu",
        "label": "DCAPE (J/kg)",
        "extend": "max",
    },
    "dcp": {
        "levels": [0.5, 1, 2, 3, 4, 6, 8],
        "cmap": "YlOrRd",
        "label": "Derecho Composite Parameter",
        "extend": "max",
    },
    "scp_enhanced": {
        "levels": [1, 2, 4, 6, 8, 10, 15, 20],
        "cmap": "OrRd",
        "label": "Enhanced Supercell Composite",
        "extend": "max",
    },
    "critical_angle": {
        "levels": [30, 45, 60, 70, 80, 90, 100, 110, 120],
        "cmap": "RdYlBu_r",
        "label": "Critical Angle (\u00b0)",
        "extend": "both",
    },
    # --- Kinematic (additional) ---
    "shear_03km": {
        "levels": [5, 10, 15, 20, 25, 30, 35, 40, 50],
        "cmap": "plasma",
        "label": "0-3km Shear (kt)",
        "extend": "max",
    },
    "lr_850_500": {
        "levels_range": (4, 10, 0.5),
        "cmap": "Reds",
        "label": "850-500mb Lapse Rate (\u00b0C/km)",
        "extend": "max",
    },
}
